"""phase3_scheduling

Revision ID: 5064976575a3
Revises: 6575ef1525a4
Create Date: 2026-08-27 12:47:31.208787

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5064976575a3'
down_revision: Union[str, None] = '6575ef1525a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('holiday_type', sa.Enum('HolidayType', native_enum=False), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holidays_date'), ['date'], unique=False)

    op.create_table('shift_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_start', sa.Time(), nullable=True),
    sa.Column('break_end', sa.Time(), nullable=True),
    sa.Column('grace_period_mins', sa.Integer(), nullable=False),
    sa.Column('late_threshold_mins', sa.Integer(), nullable=False),
    sa.Column('early_out_threshold_mins', sa.Integer(), nullable=False),
    sa.Column('overtime_threshold_mins', sa.Integer(), nullable=False),
    sa.Column('is_overnight', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employee_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('shift_template_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_rest_day', sa.Boolean(), nullable=False),
    sa.Column('schedule_status', sa.Enum('ScheduleStatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('override_start_time', sa.Time(), nullable=True),
    sa.Column('override_end_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_employee_schedule_date')
    )
    with op.batch_alter_table('employee_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_schedules_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_schedules_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_schedules_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_schedules_date'))

    op.drop_table('employee_schedules')
    op.drop_table('shift_templates')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_date'))

    op.drop_table('holidays')
    # ### end Alembic commands ###
