"""add_biometric_tables

Revision ID: 66f096c94df0
Revises: c778c652ae7b
Create Date: 2026-08-28 12:41:37.409509

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f096c94df0'
down_revision: Union[str, None] = 'c778c652ae7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometric_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('Online', 'Offline', 'Unknown', name='devicestatus'), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biometric_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.Enum('Connection Test', 'Sync', 'Push User', 'Pull Logs', 'Error', name='biometriclogtype'), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['biometric_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biometric_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biometric_logs_device_id'), ['device_id'], unique=False)

    op.create_table('employee_biometrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('finger_type', sa.Enum('Left Thumb', 'Left Index', 'Left Middle', 'Left Ring', 'Left Little', 'Right Thumb', 'Right Index', 'Right Middle', 'Right Ring', 'Right Little', name='fingertype'), nullable=False),
    sa.Column('template', sa.LargeBinary(), nullable=False),
    sa.Column('template_format', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['biometric_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'finger_type', name='uq_emp_finger')
    )
    with op.batch_alter_table('employee_biometrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_biometrics_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_biometrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_biometrics_employee_id'))

    op.drop_table('employee_biometrics')
    with op.batch_alter_table('biometric_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biometric_logs_device_id'))

    op.drop_table('biometric_logs')
    op.drop_table('biometric_devices')
    # ### end Alembic commands ###
