"""add_attendance_tables

Revision ID: c778c652ae7b
Revises: dbfb5dc50eaa
Create Date: 2026-08-28 10:42:33.345718

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c778c652ae7b'
down_revision: Union[str, None] = 'dbfb5dc50eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.Enum('In', 'Out', 'Break Out', 'Break In', name='attendanceeventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('biometric_verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('Biometric', 'Manual', 'Mock', name='attendancesource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_events_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.Column('break_out', sa.DateTime(), nullable=True),
    sa.Column('break_in', sa.DateTime(), nullable=True),
    sa.Column('time_out', sa.DateTime(), nullable=True),
    sa.Column('worked_minutes', sa.Integer(), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('undertime_minutes', sa.Integer(), nullable=False),
    sa.Column('overtime_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Present', 'Late', 'Absent', 'On Leave', 'Rest Day', 'Holiday', 'Half Day', 'Incomplete', 'Undertime', 'Overtime', name='attendancestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['employee_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_attendance_record_employee_date')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_status'), ['status'], unique=False)

    op.create_table('attendance_corrections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attendance_record_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('correction_type', sa.Enum('Time In', 'Time Out', 'Break Out', 'Break In', 'Status', name='correctiontype'), nullable=False),
    sa.Column('original_value', sa.String(length=255), nullable=False),
    sa.Column('requested_value', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Approved', 'Rejected', name='correctionstatus'), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_corrections_attendance_record_id'), ['attendance_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_corrections_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_corrections_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_corrections_status'))
        batch_op.drop_index(batch_op.f('ix_attendance_corrections_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_corrections_attendance_record_id'))

    op.drop_table('attendance_corrections')
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_status'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_date'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('attendance_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_attendance_events_employee_id'))

    op.drop_table('attendance_events')
    # ### end Alembic commands ###
