"""fix_enum_value_validation

Revision ID: dbfb5dc50eaa
Revises: 5064976575a3
Create Date: 2026-08-27 16:56:29.037530

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbfb5dc50eaa'
down_revision: Union[str, None] = '5064976575a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_schedules', schema=None) as batch_op:
        batch_op.alter_column('schedule_status',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('Active', 'Cancelled', name='schedulestatus'),
               existing_nullable=False)

    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.alter_column('holiday_type',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('Regular Holiday', 'Special Non-Working Holiday', 'Company Holiday', name='holidaytype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.alter_column('holiday_type',
               existing_type=sa.Enum('Regular Holiday', 'Special Non-Working Holiday', 'Company Holiday', name='holidaytype'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('employee_schedules', schema=None) as batch_op:
        batch_op.alter_column('schedule_status',
               existing_type=sa.Enum('Active', 'Cancelled', name='schedulestatus'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)

    # ### end Alembic commands ###
